apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed
  storageClassName: standard  # Use appropriate storage class for your cluster